# faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas a informações possivéis sobre ele  
a = input('Digite algo: ')
print('Tipo primitivo desse valor é', type(a))
print('Só tem espaços? ', a.isspace())       
print('É um número ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É Alfanúmerico? ', a.isalnum())
print('Está em maiúsculo? ', a.isupper())
print('Está em minuscúlo? ', a.islower()) 
print('Está captalizada?', a.istitle())